In [8]:
import pandas as pd

In [9]:
loan = pd.read_csv('Loan.csv')
loan

     Status CreditGrade  Amount  Age  BorrowerRate  DebtToIncome
0         0   Excellent   14500   10        0.0940         0.168
1         0   Excellent   18000    2        0.2000         0.320
2         0   Excellent   10000    5        0.2100         0.330
3         0   Excellent   10500    5        0.1200         0.330
4         0   Excellent   20000    4        0.1688         0.400
..      ...         ...     ...  ...           ...           ...
845       1        Poor    2000    6        0.2875         0.060
846       1        Poor    5000    5        0.2700         0.070
847       1        Poor    1000    5        0.2400         0.100
848       1        Poor    3300    5        0.2900         0.140
849       1        Poor    2000    4        0.2900         0.140

[850 rows x 6 columns]

In [17]:
#is.factor(loan$CreditGrade)

In [19]:
#set.seed(1)

In [21]:
#train=sample(1:850,750)